services:
  - type: web
    name: e-commerce
    env: node
    buildCommand: chmod +x ./build.sh && ./build.sh
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.x
    build:
      cacheVersion: v1
